spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-zhao-dev

---
spring:
  profiles: test
  application:
<<<<<<< HEAD
    name: microservicecloud-config-zhao-test
=======
    name: microservicecloud-config-zhao-test
>>>>>>> a2acd92147609dcab471cf230418192eb50bf816
