spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-zhao-dev

---
spring:
  profiles: test
  application:
    name: microsercicecloud-config-zhao-test